#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-settings
Version  : 4.14.2
Release  : 34
URL      : http://archive.xfce.org/src/xfce/xfce4-settings/4.14/xfce4-settings-4.14.2.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfce4-settings/4.14/xfce4-settings-4.14.2.tar.bz2
Summary  : Settings manager of the Xfce desktop
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-settings-bin = %{version}-%{release}
Requires: xfce4-settings-data = %{version}-%{release}
Requires: xfce4-settings-license = %{version}-%{release}
Requires: xfce4-settings-locales = %{version}-%{release}
BuildRequires : intltool
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(garcon-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(inputproto)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libxfce4kbd-private-3)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
Patch1: 0001-xsettings-Visual-styling.patch
Patch2: 0002-xfsettingds-Use-the-correct-stateless-desktop-file-w.patch

%description


%package bin
Summary: bin components for the xfce4-settings package.
Group: Binaries
Requires: xfce4-settings-data = %{version}-%{release}
Requires: xfce4-settings-license = %{version}-%{release}

%description bin
bin components for the xfce4-settings package.


%package data
Summary: data components for the xfce4-settings package.
Group: Data

%description data
data components for the xfce4-settings package.


%package license
Summary: license components for the xfce4-settings package.
Group: Default

%description license
license components for the xfce4-settings package.


%package locales
Summary: locales components for the xfce4-settings package.
Group: Default

%description locales
locales components for the xfce4-settings package.


%prep
%setup -q -n xfce4-settings-4.14.2
cd %{_builddir}/xfce4-settings-4.14.2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578949231
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1578949231
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-settings
cp %{_builddir}/xfce4-settings-4.14.2/COPYING %{buildroot}/usr/share/package-licenses/xfce4-settings/dfac199a7539a404407098a2541b9482279f690d
%make_install
%find_lang xfce4-settings
## install_append content
mv %{buildroot}%{_sysconfdir}/xdg %{buildroot}%{_datadir}/. && rmdir %{buildroot}%{_sysconfdir}

## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/settings/appearance-install-theme

%files bin
%defattr(-,root,root,-)
/usr/bin/xfce4-accessibility-settings
/usr/bin/xfce4-appearance-settings
/usr/bin/xfce4-display-settings
/usr/bin/xfce4-find-cursor
/usr/bin/xfce4-keyboard-settings
/usr/bin/xfce4-mime-settings
/usr/bin/xfce4-mouse-settings
/usr/bin/xfce4-settings-editor
/usr/bin/xfce4-settings-manager
/usr/bin/xfsettingsd

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-display-settings.desktop
/usr/share/applications/xfce-keyboard-settings.desktop
/usr/share/applications/xfce-mouse-settings.desktop
/usr/share/applications/xfce-settings-manager.desktop
/usr/share/applications/xfce-ui-settings.desktop
/usr/share/applications/xfce4-accessibility-settings.desktop
/usr/share/applications/xfce4-mime-settings.desktop
/usr/share/applications/xfce4-settings-editor.desktop
/usr/share/icons/hicolor/128x128/devices/xfce-display-extend.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-external.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-internal.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-mirror.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-profile.png
/usr/share/xdg/autostart/xfsettingsd.desktop
/usr/share/xdg/menus/xfce-settings-manager.menu
/usr/share/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-settings/dfac199a7539a404407098a2541b9482279f690d

%files locales -f xfce4-settings.lang
%defattr(-,root,root,-)

