#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-settings
Version  : 4.12.0
Release  : 16
URL      : http://archive.xfce.org/src/xfce/xfce4-settings/4.12/xfce4-settings-4.12.0.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfce4-settings/4.12/xfce4-settings-4.12.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-settings-bin
Requires: xfce4-settings-data
Requires: xfce4-settings-locales
BuildRequires : intltool
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(exo-1)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(garcon-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(inputproto)
BuildRequires : pkgconfig(libxfce4kbd-private-2)
BuildRequires : pkgconfig(libxfce4ui-1)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
Patch1: 0001-xsettings-Visual-styling.patch
Patch2: 0002-xfsettingds-Use-the-correct-stateless-desktop-file-w.patch

%description


%package bin
Summary: bin components for the xfce4-settings package.
Group: Binaries
Requires: xfce4-settings-data

%description bin
bin components for the xfce4-settings package.


%package data
Summary: data components for the xfce4-settings package.
Group: Data

%description data
data components for the xfce4-settings package.


%package locales
Summary: locales components for the xfce4-settings package.
Group: Default

%description locales
locales components for the xfce4-settings package.


%prep
%setup -q -n xfce4-settings-4.12.0
%patch1 -p1
%patch2 -p1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang xfce4-settings
## make_install_append content
mv %{buildroot}%{_sysconfdir}/xdg %{buildroot}%{_datadir}/. && rmdir %{buildroot}%{_sysconfdir}
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/settings/appearance-install-theme

%files bin
%defattr(-,root,root,-)
/usr/bin/xfce4-accessibility-settings
/usr/bin/xfce4-appearance-settings
/usr/bin/xfce4-display-settings
/usr/bin/xfce4-keyboard-settings
/usr/bin/xfce4-mime-settings
/usr/bin/xfce4-mouse-settings
/usr/bin/xfce4-settings-editor
/usr/bin/xfce4-settings-manager
/usr/bin/xfsettingsd

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-display-settings.desktop
/usr/share/applications/xfce-keyboard-settings.desktop
/usr/share/applications/xfce-mouse-settings.desktop
/usr/share/applications/xfce-settings-manager.desktop
/usr/share/applications/xfce-ui-settings.desktop
/usr/share/applications/xfce4-accessibility-settings.desktop
/usr/share/applications/xfce4-mime-settings.desktop
/usr/share/applications/xfce4-settings-editor.desktop
/usr/share/icons/hicolor/128x128/devices/xfce-display-extend.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-external.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-internal.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-mirror.png
/usr/share/xdg/autostart/xfsettingsd.desktop
/usr/share/xdg/menus/xfce-settings-manager.menu
/usr/share/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

%files locales -f xfce4-settings.lang 
%defattr(-,root,root,-)

