#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-settings
Version  : 4.16.4
Release  : 38
URL      : https://archive.xfce.org/src/xfce/xfce4-settings/4.16/xfce4-settings-4.16.4.tar.bz2
Source0  : https://archive.xfce.org/src/xfce/xfce4-settings/4.16/xfce4-settings-4.16.4.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-settings-bin = %{version}-%{release}
Requires: xfce4-settings-data = %{version}-%{release}
Requires: xfce4-settings-license = %{version}-%{release}
Requires: xfce4-settings-locales = %{version}-%{release}
BuildRequires : intltool
BuildRequires : pkgconfig(exo-2)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(garcon-1)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(inputproto)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libxfce4kbd-private-3)
BuildRequires : pkgconfig(libxfce4ui-2)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(libxfconf-0)
BuildRequires : pkgconfig(libxklavier)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xrandr)
Patch1: 0001-xsettings-Visual-styling.patch
Patch2: 0002-xfsettingds-Use-the-correct-stateless-desktop-file-w.patch

%description
[![License](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://gitlab.xfce.org/xfce/xfce4-settings/COPYING)

%package bin
Summary: bin components for the xfce4-settings package.
Group: Binaries
Requires: xfce4-settings-data = %{version}-%{release}
Requires: xfce4-settings-license = %{version}-%{release}

%description bin
bin components for the xfce4-settings package.


%package data
Summary: data components for the xfce4-settings package.
Group: Data

%description data
data components for the xfce4-settings package.


%package license
Summary: license components for the xfce4-settings package.
Group: Default

%description license
license components for the xfce4-settings package.


%package locales
Summary: locales components for the xfce4-settings package.
Group: Default

%description locales
locales components for the xfce4-settings package.


%prep
%setup -q -n xfce4-settings-4.16.4
cd %{_builddir}/xfce4-settings-4.16.4
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667873771
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1667873771
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfce4-settings
cp %{_builddir}/xfce4-settings-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xfce4-settings/dfac199a7539a404407098a2541b9482279f690d || :
%make_install
%find_lang xfce4-settings
## install_append content
mv %{buildroot}%{_sysconfdir}/xdg %{buildroot}%{_datadir}/. && rmdir %{buildroot}%{_sysconfdir}
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/settings/appearance-install-theme
/usr/lib64/xfce4/xfce4-compose-mail

%files bin
%defattr(-,root,root,-)
/usr/bin/xfce4-accessibility-settings
/usr/bin/xfce4-appearance-settings
/usr/bin/xfce4-display-settings
/usr/bin/xfce4-find-cursor
/usr/bin/xfce4-keyboard-settings
/usr/bin/xfce4-mime-helper
/usr/bin/xfce4-mime-settings
/usr/bin/xfce4-mouse-settings
/usr/bin/xfce4-settings-editor
/usr/bin/xfce4-settings-manager
/usr/bin/xfsettingsd

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-display-settings.desktop
/usr/share/applications/xfce-keyboard-settings.desktop
/usr/share/applications/xfce-mouse-settings.desktop
/usr/share/applications/xfce-settings-manager.desktop
/usr/share/applications/xfce-ui-settings.desktop
/usr/share/applications/xfce4-accessibility-settings.desktop
/usr/share/applications/xfce4-file-manager.desktop
/usr/share/applications/xfce4-mail-reader.desktop
/usr/share/applications/xfce4-mime-settings.desktop
/usr/share/applications/xfce4-settings-editor.desktop
/usr/share/applications/xfce4-terminal-emulator.desktop
/usr/share/applications/xfce4-web-browser.desktop
/usr/share/icons/hicolor/128x128/apps/org.xfce.filemanager.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.mailreader.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.accessibility.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.appearance.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.color.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.default-applications.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.display.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.editor.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.keyboard.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.manager.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.settings.mouse.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.terminalemulator.png
/usr/share/icons/hicolor/128x128/apps/org.xfce.webbrowser.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-extend.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-external.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-internal.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-mirror.png
/usr/share/icons/hicolor/128x128/devices/xfce-display-profile.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.filemanager.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.mailreader.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.accessibility.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.appearance.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.color.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.default-applications.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.display.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.editor.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.keyboard.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.manager.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.settings.mouse.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.terminalemulator.png
/usr/share/icons/hicolor/16x16/apps/org.xfce.webbrowser.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.filemanager.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.mailreader.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.accessibility.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.appearance.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.color.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.default-applications.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.display.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.editor.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.keyboard.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.manager.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.settings.mouse.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.terminalemulator.png
/usr/share/icons/hicolor/24x24/apps/org.xfce.webbrowser.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.filemanager.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.mailreader.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.accessibility.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.appearance.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.color.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.default-applications.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.display.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.editor.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.keyboard.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.manager.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.settings.mouse.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.terminalemulator.png
/usr/share/icons/hicolor/32x32/apps/org.xfce.webbrowser.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.filemanager.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.mailreader.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.accessibility.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.appearance.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.color.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.default-applications.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.display.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.editor.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.keyboard.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.manager.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.settings.mouse.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.terminalemulator.png
/usr/share/icons/hicolor/48x48/apps/org.xfce.webbrowser.png
/usr/share/icons/hicolor/scalable/apps/org.xfce.filemanager.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.mailreader.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.accessibility.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.appearance.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.color.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.default-applications.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.display.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.editor.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.keyboard.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.manager.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.settings.mouse.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.terminalemulator.svg
/usr/share/icons/hicolor/scalable/apps/org.xfce.webbrowser.svg
/usr/share/xdg/autostart/xfsettingsd.desktop
/usr/share/xdg/menus/xfce-settings-manager.menu
/usr/share/xdg/xfce4/helpers.rc
/usr/share/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
/usr/share/xfce4/helpers/aterm.desktop
/usr/share/xfce4/helpers/balsa.desktop
/usr/share/xfce4/helpers/brave.desktop
/usr/share/xfce4/helpers/caja.desktop
/usr/share/xfce4/helpers/chromium.desktop
/usr/share/xfce4/helpers/debian-sensible-browser.desktop
/usr/share/xfce4/helpers/debian-x-terminal-emulator.desktop
/usr/share/xfce4/helpers/dillo.desktop
/usr/share/xfce4/helpers/encompass.desktop
/usr/share/xfce4/helpers/epiphany.desktop
/usr/share/xfce4/helpers/eterm.desktop
/usr/share/xfce4/helpers/evolution.desktop
/usr/share/xfce4/helpers/firefox.desktop
/usr/share/xfce4/helpers/galeon.desktop
/usr/share/xfce4/helpers/geary.desktop
/usr/share/xfce4/helpers/gnome-terminal.desktop
/usr/share/xfce4/helpers/google-chrome.desktop
/usr/share/xfce4/helpers/icecat.desktop
/usr/share/xfce4/helpers/icedove.desktop
/usr/share/xfce4/helpers/iceweasel.desktop
/usr/share/xfce4/helpers/jumanji.desktop
/usr/share/xfce4/helpers/kmail.desktop
/usr/share/xfce4/helpers/konqueror.desktop
/usr/share/xfce4/helpers/links.desktop
/usr/share/xfce4/helpers/lynx.desktop
/usr/share/xfce4/helpers/midori.desktop
/usr/share/xfce4/helpers/mozilla-browser.desktop
/usr/share/xfce4/helpers/mozilla-mailer.desktop
/usr/share/xfce4/helpers/mutt.desktop
/usr/share/xfce4/helpers/nautilus.desktop
/usr/share/xfce4/helpers/netscape-navigator.desktop
/usr/share/xfce4/helpers/nxterm.desktop
/usr/share/xfce4/helpers/opera-browser.desktop
/usr/share/xfce4/helpers/pcmanfm-qt.desktop
/usr/share/xfce4/helpers/pcmanfm.desktop
/usr/share/xfce4/helpers/qterminal.desktop
/usr/share/xfce4/helpers/qtfm.desktop
/usr/share/xfce4/helpers/qupzilla.desktop
/usr/share/xfce4/helpers/rodent.desktop
/usr/share/xfce4/helpers/rox-filer.desktop
/usr/share/xfce4/helpers/sakura.desktop
/usr/share/xfce4/helpers/surf.desktop
/usr/share/xfce4/helpers/sylpheed-claws.desktop
/usr/share/xfce4/helpers/sylpheed.desktop
/usr/share/xfce4/helpers/terminator.desktop
/usr/share/xfce4/helpers/thunar.desktop
/usr/share/xfce4/helpers/thunderbird.desktop
/usr/share/xfce4/helpers/urxvt.desktop
/usr/share/xfce4/helpers/vimprobable2.desktop
/usr/share/xfce4/helpers/w3m.desktop
/usr/share/xfce4/helpers/xfce4-terminal.desktop
/usr/share/xfce4/helpers/xfe.desktop
/usr/share/xfce4/helpers/xterm.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfce4-settings/dfac199a7539a404407098a2541b9482279f690d

%files locales -f xfce4-settings.lang
%defattr(-,root,root,-)

